[2024-12-11 22:37:36,919] INFO listar_projetos() L88   4Projetos encontrado: - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L88  
[2024-12-11 22:37:36,952] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:37:36] "GET /projetos HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:37:46,931] INFO listar_projetos() L83   Listagem de projetos realizada com sucesso. - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L83  
[2024-12-11 22:37:46,933] INFO listar_projetos() L88   4Projetos encontrado: - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L88  
[2024-12-11 22:37:46,938] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:37:46] "GET /projetos HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:41:08,800] INFO listar_projetos() L83   Listagem de projetos realizada com sucesso. - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L83  
[2024-12-11 22:41:08,836] INFO listar_projetos() L88   4Projetos encontrado: - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L88  
[2024-12-11 22:41:08,994] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:41:08] "GET /projetos HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:41:26,239] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:41:26] "OPTIONS /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:41:26,248] INFO listar_historico() L190  Listagem de histórico do projeto ID 8 realizada com sucesso. - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L190 
[2024-12-11 22:41:26,252] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:41:26] "GET /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:42:51,966] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:42:51] "OPTIONS /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:42:51,977] INFO listar_historico() L190  Listagem de histórico do projeto ID 8 realizada com sucesso. - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L190 
[2024-12-11 22:42:51,980] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:42:51] "GET /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:43:06,755] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:43:06] "OPTIONS /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:43:06,767] INFO listar_historico() L190  Listagem de histórico do projeto ID 8 realizada com sucesso. - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L190 
[2024-12-11 22:43:06,768] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:43:06] "GET /historico HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:44:03,979] INFO listar_projetos() L83   Listagem de projetos realizada com sucesso. - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L83  
[2024-12-11 22:44:03,980] INFO listar_projetos() L88   4Projetos encontrado: - call_trace=C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py L88  
[2024-12-11 22:44:03,987] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:44:03] "GET /projetos HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:44:35,509] ERROR log_exception() L1449 Exception on /projeto [POST] - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py", line 54, in criar_projeto
    projeto = Projeto(**body.dict())
            ^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __init__
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state.py", line 481, in _initialize_instance
    with util.safe_reraise():
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\model\projeto.py", line 59, in __init__
    self.validar_custo()
  File "C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\model\projeto.py", line 87, in validar_custo
    if self.custo <= 0:
       ^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prisc\OneDrive\Documentos\PosGraduacao\DesenvolvimentoFullStack\desenvolvimento-full-stack-main\desenvolvimento-full-stack-basico\mvp-portifolio-projetos\app-api\app.py", line 70, in criar_projeto
    session.rollback()
    ^^^^^^^
UnboundLocalError: cannot access local variable 'session' where it is not associated with a value
[2024-12-11 22:44:35,511] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:44:35] "OPTIONS /projeto HTTP/1.1" 200 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
[2024-12-11 22:44:35,535] INFO _log() L225  127.0.0.1 - - [11/Dec/2024 22:44:35] "[35m[1mPOST /projeto HTTP/1.1[0m" 500 - - call_trace=C:\Users\prisc\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L225 
